wandb:
  project: "environmental-sound"
  group: "contrastive_finetune"  #base_resnet50 #contrastive_model
  name: "contrastive_finetune" #base_resnet50_aug/no_aug #contrastive_model
  bucket_name: "environmental_sound"
  tar_blob_name: "44100_npy.tar"

trainer_supervised:
  batch_size: 32
  learning_rate: 1e-3
  n_mfcc: 64
  num_classes: 50
  sample_subset: 3
  wandb_log: True
  train_size: 0.75
  val_size: 0.15
  test_size: 0.15

trainer_contrastive:
  batch_size: 32
  epochs: 10
  train_size: 0.75
  val_size: 0.15
  test_size: 0.15
  random_state: 42
  wandb_log: False
  finetune_prefix: '5-'

trainer_finetune:
  batch_size: 32
  epochs: 100
  train_size: 0.75
  val_size: 0.15
  test_size: 0.15
  random_state: 42
  wandb_log: False
  finetune_prefix: '5-'
  contrastive_checkpoint: 'contrastive-epoch=105-val_loss=3.33.ckpt'