wandb:
  project: "environmental-sound"
  group: "contrastive_finetune_v2_frozen"  #base_resnet50 #contrastive_model #contrastive_finetune
  name: "contrastive_finetune_v2_frozen" #base_resnet50_aug/no_aug #contrastive_model #contrastive_finetune
  bucket_name: "environmental_sound"
  tar_blob_name: "44100_npy_nopre.tar"
  local_npy_dir: "44100_npy_nopre"

trainer_supervised:
  batch_size: 32
  learning_rate: 1e-3
  n_mfcc: 64
  num_classes: 50
  sample_subset: 3
  wandb_log: True
  train_size: 0.75
  val_size: 0.15
  test_size: 0.15

trainer_contrastive:
  batch_size: 16
  epochs: 200
  train_size: 0.80
  val_size: 0.10
  test_size: 0.10
  seg_length: 44100
  crop_size: 128
  embedding_dim: 512
  similarity_type: 'dot' #bilinear
  temperature: 0.1
  random_state: 42
  wandb_log: False
  fold_prefix: ['1-', '2-', '3-']

trainer_selfsup:
  batch_size: 32
  epochs: 200
  train_size: 0.7
  val_size: 0.15
  test_size: 0.15
  random_state: 42
  classes: 50
  seg_length: 44100
  crop_size: 128
  embedding_dim: 512
  temperature: 0.1
  wandb_log: False
  fold_prefix: ['4-']
  contrastive_checkpoint: 'contrastive-epoch=70-val_loss=0.75.ckpt'

trainer_finetune:
  batch_size: 32
  epochs: 200
  train_size: 0.7
  val_size: 0.15
  test_size: 0.15
  random_state: 42
  classes: 50
  seg_length: 44100
  crop_size: 128
  embedding_dim: 512
  wandb_log: False
  freeze_encoder: True
  lr_downstream: 1e-4
  lr_encoder: 1e-5
  fold_prefix: [ '5-']
  contrastive_checkpoint: 'contrastive-epoch=70-val_loss=0.75.ckpt'