wandb:
  project: "environmental-sound"
  group: "contrastive_finetune"  #base_resnet50 #contrastive_model
  name: "contrastive_finetune" #base_resnet50_aug/no_aug #contrastive_model
  bucket_name: "environmental_sound"
  tar_blob_name: "44100_npy_nopre.tar"
  local_npy_dir: "44100_npy_nopre"

trainer_supervised:
  batch_size: 32
  learning_rate: 1e-3
  n_mfcc: 64
  num_classes: 50
  sample_subset: 3
  wandb_log: True
  train_size: 0.75
  val_size: 0.15
  test_size: 0.15

trainer_contrastive:
  batch_size: 16
  epochs: 200
  train_size: 0.80
  val_size: 0.10
  test_size: 0.10
  seg_length: 44100
  crop_size: 128
  embedding_dim: 512
  similarity_type: 'dot' #bilinear
  temperature: 0.1
  random_state: 42
  wandb_log: False
  finetune_prefix: ['5-', '4-']

trainer_finetune:
  batch_size: 32
  epochs: 500
  train_size: 0.8
  val_size: 0.10
  test_size: 0.10
  random_state: 42
  wandb_log: True
  finetune_prefix: ['5-', '4-']
  contrastive_checkpoint: 'contrastive-epoch=70-val_loss=0.75.ckpt'